<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EventPackagesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tour_packages')->insert([
            // EXCLUSIVE EVENTS (4)
            [
                'title' => 'BLACKPINK World Tour Manila',
                'subtitle' => 'BLACKPINK in Manila 2025',
                'overview' => 'Experience BLACKPINK live in Manila with VIP treatment. Enjoy premium tickets, hotel stay, and exclusive merchandise.',
                'content' => '<ul><li>VIP Ticket</li><li>Hotel Accommodation</li><li>Roundtrip Transfers</li><li>Official Merch Bundle</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=1200']),
                'slug' => Str::slug('BLACKPINK World Tour Manila'),
                'base_price' => 19999.00,
                'package_type' => 'event',
                'event_type' => 'exclusive',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Taylor Swift Eras Tour VIP',
                'subtitle' => 'The Eras Tour Manila 2025',
                'overview' => 'Don\'t miss Taylor Swift\'s phenomenal Eras Tour with exclusive VIP access, premium seating, and special merchandise.',
                'content' => '<ul><li>VIP Floor Ticket</li><li>5-Star Hotel Stay</li><li>Airport Transfers</li><li>Exclusive Tour Merchandise</li><li>Pre-Show Meet & Greet</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200']),
                'slug' => Str::slug('Taylor Swift Eras Tour VIP'),
                'base_price' => 24999.00,
                'package_type' => 'event',
                'event_type' => 'exclusive',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Formula 1 Singapore Grand Prix VIP',
                'subtitle' => 'F1 Night Race Premium Experience',
                'overview' => 'Watch the thrilling Formula 1 Singapore Grand Prix with VIP hospitality, paddock access, and luxury accommodation.',
                'content' => '<ul><li>Paddock Club Access</li><li>Luxury Hotel 3 Nights</li><li>Pit Lane Walk</li><li>Gourmet Dining</li><li>Private Transfers</li></ul>',
                'image_overview' => 'https://images.pexels.com/photos/12801/pexels-photo-12801.jpeg?w=800',
                'image_banner' => json_encode(['https://images.pexels.com/photos/257851/pexels-photo-257851.jpeg?w=1200']),
                'slug' => Str::slug('Formula 1 Singapore Grand Prix VIP'),
                'base_price' => 45999.00,
                'package_type' => 'event',
                'event_type' => 'exclusive',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 1,
            ],
            [
                'title' => 'Ed Sheeran Mathematics Tour',
                'subtitle' => 'Ed Sheeran Live in Manila',
                'overview' => 'Experience Ed Sheeran\'s magical performance with premium seats and exclusive backstage tour access.',
                'content' => '<ul><li>Premium Ticket</li><li>Hotel Accommodation</li><li>Backstage Tour</li><li>Signed Merchandise</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200']),
                'slug' => Str::slug('Ed Sheeran Mathematics Tour'),
                'base_price' => 18999.00,
                'package_type' => 'event',
                'event_type' => 'exclusive',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],

            // FESTIVAL EVENTS (4)
            [
                'title' => 'Sinulog Festival 2025 VIP Access',
                'subtitle' => 'Cebu City Street Parade Special',
                'overview' => 'Join the Sinulog Festival with full access to the main parade, concert events, and cultural exhibits.',
                'content' => '<ul><li>Festival Access Pass</li><li>2 Nights Hotel Stay</li><li>Guided City Tour</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1200']),
                'slug' => Str::slug('Sinulog Festival 2025'),
                'base_price' => 11999.00,
                'package_type' => 'event',
                'event_type' => 'festival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],
            [
                'title' => 'Ati-Atihan Festival Experience',
                'subtitle' => 'Kalibo Aklan Festival Package',
                'overview' => 'Immerse yourself in the "Mother of All Philippine Festivals" with street dancing, music, and cultural celebrations.',
                'content' => '<ul><li>Festival Pass</li><li>3 Nights Accommodation</li><li>Traditional Costume Rental</li><li>Island Tour</li></ul>',
                'image_overview' => 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?w=800',
                'image_banner' => json_encode(['https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?w=1200']),
                'slug' => Str::slug('Ati-Atihan Festival Experience'),
                'base_price' => 13499.00,
                'package_type' => 'event',
                'event_type' => 'festival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],
            [
                'title' => 'Panagbenga Flower Festival',
                'subtitle' => 'Baguio Blooming Season',
                'overview' => 'Celebrate spring in Baguio with the colorful Panagbenga Festival featuring grand float parades and street dancing.',
                'content' => '<ul><li>Festival Viewing Pass</li><li>4 Days 3 Nights Hotel</li><li>City Tour</li><li>Strawberry Farm Visit</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1463595373836-6e0b0a8ee322?w=1200']),
                'slug' => Str::slug('Panagbenga Flower Festival'),
                'base_price' => 9999.00,
                'package_type' => 'event',
                'event_type' => 'festival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'MassKara Festival Bacolod',
                'subtitle' => 'Festival of Smiles',
                'overview' => 'Join the vibrant MassKara Festival with colorful masks, street dance competitions, and food festivals.',
                'content' => '<ul><li>VIP Festival Pass</li><li>2 Nights Hotel</li><li>Mask Making Workshop</li><li>Food Tour</li></ul>',
                'image_overview' => 'https://images.pexels.com/photos/1729797/pexels-photo-1729797.jpeg?w=800',
                'image_banner' => json_encode(['https://images.pexels.com/photos/1306815/pexels-photo-1306815.jpeg?w=1200']),
                'slug' => Str::slug('MassKara Festival Bacolod'),
                'base_price' => 10499.00,
                'package_type' => 'event',
                'event_type' => 'festival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],

            // SEASONAL EVENTS (4)
            [
                'title' => 'Christmas Gala Night 2025',
                'subtitle' => 'Holiday Special Dinner and Show',
                'overview' => 'Celebrate the holidays with a luxurious gala dinner, live performances, and fireworks display.',
                'content' => '<ul><li>Gala Dinner</li><li>Live Music & Entertainment</li><li>Fireworks Display</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=1200']),
                'slug' => Str::slug('Christmas Gala Night 2025'),
                'base_price' => 7499.00,
                'package_type' => 'event',
                'event_type' => 'seasonal',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'Valentine\'s Day Romantic Cruise',
                'subtitle' => 'Manila Bay Sunset Cruise',
                'overview' => 'Celebrate love with a romantic dinner cruise featuring live music, gourmet dining, and stunning sunset views.',
                'content' => '<ul><li>Luxury Yacht Cruise</li><li>5-Course Dinner</li><li>Live Orchestra</li><li>Champagne Toast</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1200']),
                'slug' => Str::slug('Valentine\'s Day Romantic Cruise'),
                'base_price' => 8999.00,
                'package_type' => 'event',
                'event_type' => 'seasonal',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],
            [
                'title' => 'Halloween Horror Nights',
                'subtitle' => 'Spooky Theme Park Experience',
                'overview' => 'Get scared at the ultimate Halloween event with haunted houses, scare zones, and horror-themed attractions.',
                'content' => '<ul><li>Park Admission</li><li>Express Pass</li><li>Hotel Stay</li><li>Costume Party Access</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1570362261138-034b8a5d4ba7?w=1200']),
                'slug' => Str::slug('Halloween Horror Nights'),
                'base_price' => 6999.00,
                'package_type' => 'event',
                'event_type' => 'seasonal',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'Easter Island Hopping Adventure',
                'subtitle' => 'Spring Break Beach Getaway',
                'overview' => 'Celebrate Easter with a tropical island hopping tour featuring pristine beaches and water activities.',
                'content' => '<ul><li>3 Islands Tour</li><li>2 Nights Resort Stay</li><li>Snorkeling Gear</li><li>Easter Brunch</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200']),
                'slug' => Str::slug('Easter Island Hopping Adventure'),
                'base_price' => 12999.00,
                'package_type' => 'event',
                'event_type' => 'seasonal',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],

            // POPULAR EVENTS (4)
            [
                'title' => 'Summer Beats Music Fest 2025',
                'subtitle' => 'Beach Party and Concert',
                'overview' => 'Enjoy summer vibes with top DJs, live bands, and a beachside concert weekend.',
                'content' => '<ul><li>Festival Pass</li><li>1 Night Accommodation</li><li>Beach Party Access</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200']),
                'slug' => Str::slug('Summer Beats Music Fest 2025'),
                'base_price' => 8999.00,
                'package_type' => 'event',
                'event_type' => 'popular',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 1,
            ],
            [
                'title' => 'Wanderland Music & Arts Festival',
                'subtitle' => 'Indie Music and Art Celebration',
                'overview' => 'Experience the best of indie music with international and local artists in a vibrant outdoor setting.',
                'content' => '<ul><li>2-Day Festival Pass</li><li>Camping Option</li><li>Food & Drinks Voucher</li><li>Art Market Access</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1200']),
                'slug' => Str::slug('Wanderland Music & Arts Festival'),
                'base_price' => 7999.00,
                'package_type' => 'event',
                'event_type' => 'popular',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],
            [
                'title' => 'Ultra Philippines EDM Festival',
                'subtitle' => 'Electronic Dance Music Extravaganza',
                'overview' => 'Dance the night away with world-class DJs at Asia\'s premier electronic music festival.',
                'content' => '<ul><li>General Admission</li><li>Hotel Package</li><li>After Party Access</li><li>Festival Merchandise</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200']),
                'slug' => Str::slug('Ultra Philippines EDM Festival'),
                'base_price' => 9499.00,
                'package_type' => 'event',
                'event_type' => 'popular',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'Manila International Book Fair',
                'subtitle' => 'Literary Festival and Book Expo',
                'overview' => 'Meet your favorite authors, discover new books, and enjoy workshops at the biggest book fair in the Philippines.',
                'content' => '<ul><li>3-Day Pass</li><li>Author Meet & Greet</li><li>Workshop Access</li><li>Book Vouchers</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200']),
                'slug' => Str::slug('Manila International Book Fair'),
                'base_price' => 2999.00,
                'package_type' => 'event',
                'event_type' => 'popular',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 3,
            ],

            // LIMITED TIME EVENTS (4)
            [
                'title' => 'New Year Countdown 2026',
                'subtitle' => 'Midnight Celebration Party',
                'overview' => 'Ring in the new year with a grand fireworks display, live music, and exclusive access to the VIP zone.',
                'content' => '<ul><li>VIP Access</li><li>Drinks & Snacks</li><li>Fireworks Show</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1492447273231-0f8fecec1e3a?w=1200']),
                'slug' => Str::slug('New Year Countdown 2026'),
                'base_price' => 5999.00,
                'package_type' => 'event',
                'event_type' => 'limited_time',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'Black Friday Shopping Spree',
                'subtitle' => 'Exclusive Mall Shopping Event',
                'overview' => 'Shop till you drop with exclusive access to Black Friday sales, VIP lounge, and personal shopper service.',
                'content' => '<ul><li>VIP Shopping Pass</li><li>Personal Shopper</li><li>Lounge Access</li><li>Shopping Vouchers</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200']),
                'slug' => Str::slug('Black Friday Shopping Spree'),
                'base_price' => 3999.00,
                'package_type' => 'event',
                'event_type' => 'limited_time',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => '24-Hour Food Festival',
                'subtitle' => 'Ultimate Foodie Experience',
                'overview' => 'Indulge in a 24-hour culinary adventure featuring top restaurants, food trucks, and cooking demonstrations.',
                'content' => '<ul><li>All-Access Food Pass</li><li>Celebrity Chef Demo</li><li>Unlimited Tastings</li><li>Recipe Book</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200']),
                'slug' => Str::slug('24-Hour Food Festival'),
                'base_price' => 4999.00,
                'package_type' => 'event',
                'event_type' => 'limited_time',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Weekend Art Market Special',
                'subtitle' => 'Limited Weekend Only Event',
                'overview' => 'Discover unique artworks, crafts, and handmade items from local artists in this exclusive weekend market.',
                'content' => '<ul><li>Market Entry</li><li>Artist Workshop</li><li>Shopping Bag</li><li>Refreshments</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1472745942893-3990a6e8c95e?w=1200']),
                'slug' => Str::slug('Weekend Art Market Special'),
                'base_price' => 1999.00,
                'package_type' => 'event',
                'event_type' => 'limited_time',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],

            // NEW ARRIVAL EVENTS (4)
            [
                'title' => 'Comic-Con Manila 2025',
                'subtitle' => 'Pop Culture and Cosplay Convention',
                'overview' => 'A paradise for pop culture fans—comics, games, movies, and cosplay in one big event!',
                'content' => '<ul><li>3-Day Pass</li><li>Hotel Stay</li><li>Meet & Greet Access</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=1200']),
                'slug' => Str::slug('Comic-Con Manila 2025'),
                'base_price' => 9999.00,
                'package_type' => 'event',
                'event_type' => 'new_arrival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Gaming Expo Asia 2025',
                'subtitle' => 'Latest Games and Technology Showcase',
                'overview' => 'Be the first to experience upcoming games, VR technology, and meet gaming influencers at Asia\'s premier gaming expo.',
                'content' => '<ul><li>2-Day Expo Pass</li><li>Early Access</li><li>Gaming Merchandise</li><li>Tournament Entry</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200']),
                'slug' => Str::slug('Gaming Expo Asia 2025'),
                'base_price' => 5999.00,
                'package_type' => 'event',
                'event_type' => 'new_arrival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Virtual Reality Experience Center',
                'subtitle' => 'Next-Gen VR Entertainment',
                'overview' => 'Step into the future with cutting-edge VR experiences, from gaming to virtual travel adventures.',
                'content' => '<ul><li>4-Hour VR Session</li><li>Multiple Experience Zones</li><li>VR Headset Rental</li><li>Refreshments</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=1200']),
                'slug' => Str::slug('Virtual Reality Experience Center'),
                'base_price' => 3499.00,
                'package_type' => 'event',
                'event_type' => 'new_arrival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],
            [
                'title' => 'K-Pop Fan Meeting 2025',
                'subtitle' => 'Meet Your Favorite K-Pop Stars',
                'overview' => 'Get up close with K-Pop idols in this newly announced fan meeting event with games, performances, and photo ops.',
                'content' => '<ul><li>Fan Meeting Ticket</li><li>Group Photo</li><li>Autograph Session</li><li>Official Light Stick</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=1200']),
                'slug' => Str::slug('K-Pop Fan Meeting 2025'),
                'base_price' => 8999.00,
                'package_type' => 'event',
                'event_type' => 'new_arrival',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 2,
            ],

            // FLASH SALE EVENTS (4)
            [
                'title' => 'Flash Sale: Esports Arena Pass',
                'subtitle' => 'Limited-Time Esports Bundle',
                'overview' => 'Get massive discounts on esports arena tickets and exclusive fan gear for a limited time only!',
                'content' => '<ul><li>Esports Ticket</li><li>Exclusive Merch</li><li>Discounted Voucher</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200']),
                'slug' => Str::slug('Flash Sale Esports Arena Pass'),
                'base_price' => 2999.00,
                'package_type' => 'event',
                'event_type' => 'flash_sale',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Flash Deal: Water Park Day Pass',
                'subtitle' => '50% Off Today Only',
                'overview' => 'Beat the heat with this amazing flash deal! Enjoy unlimited access to all water park attractions.',
                'content' => '<ul><li>Full Day Pass</li><li>Locker Rental</li><li>Meal Voucher</li><li>Souvenir Photo</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1561459508-d8d8e58c38f7?w=1200']),
                'slug' => Str::slug('Flash Deal Water Park Day Pass'),
                'base_price' => 1499.00,
                'package_type' => 'event',
                'event_type' => 'flash_sale',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Lightning Deal: Spa & Wellness Day',
                'subtitle' => 'Flash Sale Relaxation Package',
                'overview' => 'Unwind with this limited-time spa package featuring massage, facial, and wellness treatments at unbeatable prices.',
                'content' => '<ul><li>Full Body Massage</li><li>Facial Treatment</li><li>Sauna Access</li><li>Healthy Lunch</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200']),
                'slug' => Str::slug('Lightning Deal Spa & Wellness Day'),
                'base_price' => 3499.00,
                'package_type' => 'event',
                'event_type' => 'flash_sale',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
            [
                'title' => 'Flash Sale: Theme Park Adventure',
                'subtitle' => 'Limited Hourly Offer',
                'overview' => 'Grab this flash sale for discounted theme park tickets with fast pass access and meal inclusions!',
                'content' => '<ul><li>Park Admission</li><li>Fast Pass</li><li>Meal Combo</li><li>Parking</li></ul>',
                'image_overview' => 'https://images.unsplash.com/photo-1594623930572-300a3011d9ae?w=800',
                'image_banner' => json_encode(['https://images.unsplash.com/photo-1579308247423-693669aa3e0c?w=1200']),
                'slug' => Str::slug('Flash Sale Theme Park Adventure'),
                'base_price' => 2499.00,
                'package_type' => 'event',
                'event_type' => 'flash_sale',
                'created_at' => now(),
                'updated_at' => now(),
                'preferred_days' => 4,
            ],
        ]);
    }
}
